### ISSUE TITLE
Typo in the name (Manger -> Manager)

### ISSUE THREAD

**Issue by adamnapieralski** [eficode/JiraInstanceMangerRest#7]
It is confusing during usage of the library and makes the code prone to errors.

**Comment by farthinder** [comment]
Arrgh I`ll look in to this, but will likely break any dependency on the project.

**Comment by farthinder** [comment]
This problem was fixed in 1.1.0. 
This likley breaks the repo urls you might have in pom files, the correct one is now: https://github.com/eficode/JiraInstanceManagerRest/raw/packages/repository/

Check the README in 1.1.0 for other breaking changes.
